[can]
interface = "can0"

[web]
port = 8081
listen = "0.0.0.0"
static_path = "ui/dist"
prometheus_metrics = true

[grpc]
listen = "0.0.0.0:50051"

[database]
# connection_string = "postgres://caniot:caniot@localhost/caniot"
# connection_string = "sqlite://caniot.db"
retry_interval = 1
# retries = 3

[caniot]
pending_queries_default_timeout = 1000 # ms
action_default_timeout = 1000          # ms
inernal_api_mpsc_size = 20             # ms

[caniot.devices]
heaters_did = 1
garage_did = 16
outdoor_alarm_did = 24

[copro]
listen_ip = "192.0.3.1"
listen_port = 4000
