[can]
interface = "can0"

[web]
port = 8080
listen = "0.0.0.0"
static_path = "ui/dist"
prometheus_metrics = true

[grpc]
listen = "[::]:50051"

[database]
connection_string = "postgres://caniot:caniot@localhost/caniot"

[caniot_controller]
pending_queries_default_timeout = 1000 # ms
action_default_timeout = 1000          # ms
inernal_api_mpsc_size = 20             # ms

[caniot_controller.devices]
heaters_did = 1
garage_did = 16
outdoor_alarm_did = 24
